#!/bin/bash

# make sure submodules are synced
git submodule update --init --recursive

# set variables
GLFW_SETTINGS="-DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DGLFW_INSTALL=OFF"
BUILD_TYPE="$1"

# shift arguments
shift

# check if no argument was passed for BUILD_TYPE
if [[ -z "$BUILD_TYPE" ]]; then
    # if no argument was passed, set the build type to release
    BUILD_TYPE="Release"
fi

# parse $OSTYPE
if [[ "$OSTYPE" == "linux-gnu" ]]; then
    OS_NAME="Linux"
    OS_TYPE="linux"
elif [[ "$OSTYPE" == "darwin" ]]; then
    OS_NAME="MacOS"
    OS_TYPE="macosx"
else
    OS_NAME="Other"
    OS_TYPE="other"
fi

# echo back information
SEPARATOR="################################################################################"
echo "$SEPARATOR"
echo "Configuring vkplayground CMake projects"
echo "Build type: $BUILD_TYPE"
echo "Operating system: $OS_NAME"
echo "$SEPARATOR"

# configure
cmake . -B build/ -G "Unix Makefiles" -DBUILD_SHARED_LIBS=OFF -DBUILD_PLAYGROUND_APPLICATION=ON $GLFW_SETTINGS -DCMAKE_BUILD_TYPE="$BUILD_TYPE" "$@"