#pragma once
#define GLFW_INCLUDE_VULKAN
#include <GLFW/glfw3.h>
#define GLM_FORCE_RADIANS
#define GLM_FORCE_DEPTH_ZERO_TO_ONE
#include <glm/glm.hpp>
#include <glm/mat4x4.hpp>
#include <spdlog/spdlog.h>
#include <string>
#include <vector>
#include <iostream>
#include <unordered_map>
#include <map>
#include <memory>
#include <stdexcept>
#include <functional>
#include <optional>
#include <set>
#include <algorithm>
#include <array>
#include <cstdint>
#include <stddef.h>
