#pragma once
#define GLFW_INCLUDE_VULKAN
#include <GLFW/glfw3.h>
#define GLM_FORCE_RADIANS
#define GLM_FORCE_DEPTH_ZERO_TO_ONE
#include <glm/glm.hpp>
#include <glm/mat4x4.hpp>
#include <string>
#include <vector>
#include <iostream>
#include <unordered_map>
#include <memory>
#include <cstdint>
#include <stddef.h>
