name: build
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: setup node
        shell: bash
        run: |
          curl -fsSL https://deb.nodesource.com/setup_12.x | sudo -E bash -
          sudo apt-get update
          sudo apt-get install -y nodejs
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.6
          architecture: x64
      - name: configure project
        shell: bash
        run: |
          sudo apt-get update
          python -m scripts config
      - name: build project
        shell: bash
        run: |
          make -C build -j 8